/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "MessageRole".
 */
export type MessageRole = "user" | "assistant" | "system";
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "MessageType".
 */
export type MessageType = "text" | "tool_use" | "tool_result" | "thinking" | "state_change" | "error";
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "AgentStateType".
 */
export type AgentStateType = "running" | "idle" | "permission_waiting" | "error" | "stopped";
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "ClientEvent".
 */
export type ClientEvent =
  | {
      sessionId: string;
      type: "subscribe:session";
      [k: string]: unknown;
    }
  | {
      sessionId: string;
      type: "unsubscribe:session";
      [k: string]: unknown;
    };
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "SearchScope".
 */
export type SearchScope = "project_name" | "current_task" | "working_directory" | "content";
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "ServerEvent".
 */
export type ServerEvent =
  | {
      sessions: AgentSessionSummary[];
      type: "sessions:init";
      [k: string]: unknown;
    }
  | {
      session: AgentSessionSummary;
      type: "session:discovered";
      [k: string]: unknown;
    }
  | {
      sessionId: string;
      type: "session:removed";
      [k: string]: unknown;
    }
  | {
      current: AgentStateType;
      previous: AgentStateType;
      session: AgentSessionSummary;
      sessionId: string;
      type: "session:state_changed";
      [k: string]: unknown;
    }
  | {
      message: AgentMessage;
      sessionId: string;
      type: "session:new_message";
      [k: string]: unknown;
    }
  | {
      messages: AgentMessage[];
      sessionId: string;
      type: "session:messages_init";
      [k: string]: unknown;
    }
  | {
      sessionId: string;
      type: "session:usage_updated";
      usage: CumulativeUsage;
      [k: string]: unknown;
    }
  | {
      gitStatus: GitStatus;
      sessionId: string;
      type: "session:git_status_updated";
      [k: string]: unknown;
    };

export interface AgentsDashboard {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "AgentMessage".
 */
export interface AgentMessage {
  content: string;
  id: string;
  metadata?: {
    [k: string]: unknown;
  } | null;
  role: MessageRole;
  sessionId: string;
  timestamp: string;
  type: MessageType;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "AgentSessionDetail".
 */
export interface AgentSessionDetail {
  cumulativeUsage: CumulativeUsage;
  currentTask: string;
  gitStatus: GitStatus;
  lastActivityAt: string;
  messages: AgentMessage[];
  model: string;
  projectName: string;
  projectPath: string;
  provider: string;
  sessionId: string;
  startedAt: string;
  state: AgentStateType;
  workingDirectory: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "CumulativeUsage".
 */
export interface CumulativeUsage {
  cacheCreationTokens: number;
  cacheReadTokens: number;
  estimatedCost: number;
  inputTokens: number;
  outputTokens: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "GitStatus".
 */
export interface GitStatus {
  additions: number;
  branch: string;
  deletions: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "AgentSessionSummary".
 */
export interface AgentSessionSummary {
  cumulativeUsage: CumulativeUsage;
  currentTask: string;
  gitStatus: GitStatus;
  lastActivityAt: string;
  model: string;
  projectName: string;
  projectPath: string;
  provider: string;
  sessionId: string;
  startedAt: string;
  state: AgentStateType;
  workingDirectory: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "SearchMatch".
 */
export interface SearchMatch {
  content: string;
  messageRole: MessageRole;
  messageType: MessageType;
  scope: SearchScope;
  timestamp: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "SearchResponse".
 */
export interface SearchResponse {
  query: string;
  results: SessionSearchResult[];
  totalSessions: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `AgentsDashboard`'s JSON-Schema
 * via the `definition` "SessionSearchResult".
 */
export interface SessionSearchResult {
  matchCount: number;
  matches: SearchMatch[];
  session: AgentSessionSummary;
  [k: string]: unknown;
}
